### ISSUE TITLE
Typo in shortcode-chart-js-plusplus.yaml

### ISSUE THREAD

**Issue by fugo** [sal0max/grav-plugin-shortcode-chart-js-plusplus#2]
there are to much numbers in the hex code color at the default plugin configuration:
``#65a0e999`` 

```
enabled: true
chart:
  backgroundColor: '#65a0e999' 
  borderColor: '#65a0e9'
  pointBackgroundColor: '#65a0e9'
  pointBorderColor: '#65a0e9'
```
